<?php

/* custom routes generated by CRUD */


Route::group(array('prefix' => 'admin'), function () {Route::resource('events', 'EventsController');
	Route::get('events/{id}/delete', array('as' => 'admin.events.delete', 'uses' => 'EventsController@getDelete'));
	Route::get('events/{id}/confirm-delete', array('as' => 'admin.events.confirm-delete', 'uses' => 'EventsController@getModalDelete'));
});

Route::group(array('prefix' => 'admin'), function () {Route::resource('usergroups', 'UsergroupsController');
	Route::get('usergroups/{id}/delete', array('as' => 'admin.usergroups.delete', 'uses' => 'UsergroupsController@getDelete'));
	Route::get('usergroups/{id}/confirm-delete', array('as' => 'admin.usergroups.confirm-delete', 'uses' => 'UsergroupsController@getModalDelete'));
});

Route::group(array('prefix' => 'admin'), function () {
	Route::resource('eventcategories', 'EventcategoriesController');
	Route::get('eventcategories/{id}/delete', array('as' => 'admin.eventcategories.delete', 'uses' => 'EventcategoriesController@getDelete'));
	Route::get('eventcategories/{id}/confirm-delete', array('as' => 'admin.eventcategories.confirm-delete', 'uses' => 'EventcategoriesController@getModalDelete'));
});
